[package]
name="elk-utils"
version="2.0.1"
authors=["Lionel Karlen"]
entrypoint="lib.typ"
license="MIT-0"
description="A set of formatting utilities to ensure cohesion between my typesetting"

[template]
path="template"
entrypoint="main.typ"
